# Generated by Django 5.2.4 on 2025-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='link',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='news',
            name='recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default='(No news text)'),
        ),
        migrations.AddField(
            model_name='news',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='publication',
            name='codeLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='conference',
            field=models.CharField(default='Unknown Conference', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='field',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='paperLink',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='type',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='Jan', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(default='Unknown Author'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='Untitled Paper', max_length=512),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
    ]
