# Generated by Django 5.2.4 on 2025-07-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_news_content_remove_news_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='field',
        ),
    ]
