# Generated by Django 5.2.4 on 2025-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teammember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=255)),
                ('role', models.CharField(blank=True, default='Frontend Developer', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('projects', models.TextField(blank=True, default='project1, project2')),
                ('member_since', models.CharField(blank=True, default='2021', max_length=4)),
                ('isActive', models.BooleanField(default=True)),
                ('team', models.CharField(choices=[('lead', 'Team Lead'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer')], default='lead', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('March', 'March'), ('Apr', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(default='Author1, Author2, ...'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, default='Department of Information Technology', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('collaborator', 'Collaborator'), ('student', 'Student'), ('scholar', 'Scholar'), ('project', 'Project Staff')], default='faculty', max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='university',
            field=models.CharField(blank=True, default='NIT Srinagar', max_length=255),
        ),
    ]
